format = """
[░▒▓](#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$fill\
$nodejs\
$python\
$rust\
$golang\
$php\
\n
$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "../"

[git_branch]
symbol = " "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
disabled = false

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[nodejs]
symbol = " "
format = '[[  $symbol($version) ](fg:#68A063)]($style)'

[python]
symbol = " "
format = '[[  ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))](fg:#4B8BBE)]($style)'

[rust]
symbol = " "
format = '[[  $symbol($version) ](fg:#dea584)]($style)'

[golang]
# symbol = "󰟓 "
symbol = " "
format = '[[  $symbol($version) ](fg:#00ADD8)]($style)'

[c]
symbol = " "
format = '[[  $symbol($version) ](fg:#A8B9CC)]($style)'

[cpp]
symbol = " "
format = '[[  $symbol($version) ](fg:#00599C)]($style)'

[java]
symbol = " "
format = '[[  $symbol($version) ](fg:#007396)]($style)'

[kotlin]
symbol = " "
format = '[[  $symbol($version) ](fg:#7F52FF)]($style)'

[lua]
symbol = " "
format = '[[  $symbol($version) ](fg:#2C2D72)]($style)'

[haskell]
symbol = " "
format = '[[  $symbol($version) ](fg:#5D4F85)]($style)'

[php]
symbol = " "
format = '[[  $symbol($version) ](fg:#4F5D95)]($style)'

[character]
success_symbol =' [>](bold blue)'
error_symbol = ' [>](bold red) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
